name: wordling
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  cloud_firestore: ^4.9.0
  firebase_core: ^2.17.0
  flutter_local_notifications: ^16.1.0
  firebase_messaging: ^14.6.9
  grock: ^0.4.3
  onesignal_flutter: ^5.0.0
  shared_preferences: ^2.2.1
  cupertino_icons: ^1.0.2
  cron: ^0.5.1
  sqflite: ^2.3.0
  circular_menu: ^2.0.1
  flutter_animate: ^4.2.0+1
  android_alarm_manager_plus: ^3.0.2
  flutter_background_service: ^5.0.1
  easy_splash_screen: ^1.0.4
  flutter_onboarding_slider: ^1.0.10
  permission_handler: ^11.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/texts/
    - assets/images/opening/
    - lib/dictionary/

  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-VariableFont_wght.ttf

